= Conditional Probability
:Author:        Hassan el Hassan
:Email:         <hassan.el.hassan@vub.com>
:Date:          02/07/2020
:toc:           
:toclevels:     4
:sectnums: 
:sectnumlevels: 4
:xrefstyle:     short
:imagesdir:     images
:hardbreaks: 


== Task 

Suppose a family has 2 children, one of which is a boy. What is the probability that both children are boys?

.Task URL
[%collapsible]
====
https://www.hackerrank.com/challenges/s10-mcq-4/problem
====

== Solution 

1/3

== Explanation
### Abbreviations Used

[width=40%]
|=============
|B  |Boy     
|G  |Girl        
|=============


### Experiment
The probability two children being boys given one child is a boy =  P(BB|B).


### Sample Space
there are four equally probable events:

[options="header"]
[width=40%]
|=============
|First child|Second child
|Boy        |Boy     
|Boy        |Girl        
|Girl       |Boy       
|Girl       |Girl     
|=============

### Event (BB and B)
That two children being boys: {{B,B}} = 1
The probability of this event, P(BB and B) = 1/4


### Event (B)
That one child is a boy out of two children: {{B,B},{B,G},{G,B}} = 3
The probability of this event, P(B) = 3/4

### Probability Calculation Event (BB|B)

#### The Easy Approach
This can easily be solved using the table above.
Out of the 3 posibilities of at least one child being a boy {{B,B},{B,G},{G,B}} only 1 is two boys {{B,B}}, so 1/3.

#### The Hard Approach

P(BB|B)= P(BB and B) / P(B) = (1/4) / (3/4) = 1/3

